-- Actors table + storage setup for FilmChin

create table if not exists public.actors (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  profile_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at_actors()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at_actors on public.actors;
create trigger trg_set_updated_at_actors
before update on public.actors
for each row
execute procedure public.set_updated_at_actors();

alter table public.actors enable row level security;

-- Public read for site pages
create policy if not exists "actors_public_read"
on public.actors
for select
using (true);

-- Authenticated admin write (adapt if you use custom admin checks)
create policy if not exists "actors_admin_write"
on public.actors
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

-- Storage bucket for actor profile images
insert into storage.buckets (id, name, public)
values ('actor-profiles', 'actor-profiles', true)
on conflict (id) do nothing;

-- Public read access to actor profile files
create policy if not exists "actor_profiles_public_read"
on storage.objects
for select
using (bucket_id = 'actor-profiles');

-- Authenticated upload/update/delete in actor-profiles bucket
create policy if not exists "actor_profiles_auth_insert"
on storage.objects
for insert
with check (bucket_id = 'actor-profiles' and auth.role() = 'authenticated');

create policy if not exists "actor_profiles_auth_update"
on storage.objects
for update
using (bucket_id = 'actor-profiles' and auth.role() = 'authenticated')
with check (bucket_id = 'actor-profiles' and auth.role() = 'authenticated');

create policy if not exists "actor_profiles_auth_delete"
on storage.objects
for delete
using (bucket_id = 'actor-profiles' and auth.role() = 'authenticated');
